In [1]:
import numpy as np
arr1=np.array([1,2,3,4,5,6])
arr1=np.flip(arr1)
print(arr1)

[6 5 4 3 2 1]


In [ ]:
arr2=np.array([[1,2,3],[2,4,5],[1,2,3]])
arr3=arr2.flatten()
arr4=np.ravel(arr2)
print(arr3)
print(arr4)

[1 2 3 2 4 5 1 2 3]
[1 2 3 2 4 5 1 2 3]


In [ ]:
a=np.array([[1,2],[3,4]])
b=np.array([[1,2],[3,4]])
print(a==b)
print(np.array_equal(a,b))

[[ True  True]
 [ True  True]]
True


In [2]:
x=np.array([1,2,3,4,5,1,2,1,1,1])
y=np.array([1,1,1,2,3,4,2,4,3,3])
count1=np.bincount(x)
max_frequency1=np.argmax(count1)
indices1=np.where(x==max_frequency1)
print(max_frequency1)
print(indices1)
count2=np.bincount(y)
max_frequency2=np.argmax(count2)
indices2=np.where(y==max_frequency2)
print(max_frequency2)
print(indices2)

1
(array([0, 5, 7, 8, 9]),)
1
(array([0, 1, 2]),)


In [3]:
gfg=np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')
sum_all=np.sum(gfg)
print(f'sum of all elements: {sum_all}')
sum_rows=np.sum(gfg,axis=1)
print(f'sum of rows: {sum_rows}')
sum_cols=np.sum(gfg,axis=0)
print(f'sum of columns: {sum_cols}')

sum of all elements: 45
sum of rows: [[14]
 [16]
 [15]]
sum of columns: [[20  9 16]]


In [4]:
n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]])
sum_diag=np.trace(n_array)
print(f'sum of diaognals: {sum_diag}')
eigenvalues,eigenvectors=np.linalg.eig(n_array)
print(f'eigenvalues are: {eigenvalues}')
print(f'eigenvectors are: {eigenvectors}')
inv_n_array=np.linalg.inv(n_array)
det_n_array=np.linalg.det(n_array)
print(f'inverse: {inv_n_array}')
print(f'determinant: {det_n_array}')

sum of diaognals: 176
eigenvalues are: [98.16835147 28.097044   49.73460452]
eigenvectors are: [[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]
inverse: [[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]
determinant: 137180.0000000001


In [7]:
p1 = np.array([[1, 2], [2, 3]])
q1 = np.array([[4, 5], [6, 7]])
multi1=np.dot(p1,q1)
print(f"multiplication (i): {multi1}")
combined1=np.vstack((p1.flatten(),q1.flatten()))
covariance1=np.cov(combined1)
print(f'covariance (i): {covariance1}')
p2 = np.array([[1, 2], [2, 3], [4, 5]])
q2 = np.array([[4, 5, 1], [6, 7, 2]])
multi2=np.dot(p2,q2)
print(f'multiplication (ii): {multi2}')
combined2=np.vstack((p2.flatten(),q2.flatten()))
covariance2=np.cov(combined2)
print(f'covariance (ii): {covariance2}')

multiplication (i): [[16 19]
 [26 31]]
covariance (i): [[0.66666667 1.        ]
 [1.         1.66666667]]
multiplication (ii): [[16 19  5]
 [26 31  8]
 [46 55 14]]
covariance (ii): [[2.16666667 0.23333333]
 [0.23333333 5.36666667]]


In [11]:
x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])
inner_product=np.inner(x,y)
print(f'inner product is: {inner_product}')
outer_product=np.outer(x,y)
print(f'outer product is: {outer_product}')
flat_x=x.flatten()
flat_y=y.flatten()
cartesian_product = np.array(np.meshgrid(flat_x, flat_y)).T.reshape(-1, 2)
print(f'cartesian product is: {cartesian_product}')

inner product is: [[17 52]
 [13 62]]
outer product is: [[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]
cartesian product is: [[ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]
 [ 3 10]
 [ 3  3]
 [ 4  1]
 [ 4  5]
 [ 4  0]
 [ 4  5]
 [ 4 10]
 [ 4  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]
 [ 3 10]
 [ 3  3]
 [ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 9  1]
 [ 9  5]
 [ 9  0]
 [ 9  5]
 [ 9 10]
 [ 9  3]]


In [15]:
array = np.array([[1, -2, 3],[-4, 5, -6]])
array_abs=np.abs(array)
print(f'array with absolute values: {array_abs}')
flat_array=array.flatten()
per_25_flat=np.percentile(flat_array,25)
per_50_flat=np.percentile(flat_array,50)
per_75_flat=np.percentile(flat_array,75)
mean_flat=np.mean(flat_array)
median_flat=np.median(flat_array)
std_dev_flat=np.std(flat_array)
print(f'25th %ile for flattened array: {per_25_flat}')
print(f'50th %ile for flattened array: {per_50_flat}')
print(f'75th %ile for flattened array: {per_75_flat}')
print(f'mean for flattened array: {mean_flat}')
print(f'median for flattened array: {median_flat}')
print(f'standard deviation for flattened array: {std_dev_flat}')
for i in range(array.shape[1]):
  col=array[:,i]
  print(f'column {i+1}')
  print(f'25th %ile: {np.percentile(col,25)}')
  print(f'50th %ile: {np.percentile(col,50)}')
  print(f'75th %ile: {np.percentile(col,75)}')
  print(f'mean: {np.mean(col)}')
  print(f'median: {np.median(col)}')
  print(f'standard deviation: {np.std(col)}')
for i in range(array.shape[0]):
  row=array[i,:]
  print(f'row {i+1}')
  print(f'25th %ile: {np.percentile(row,25)}')
  print(f'50th %ile: {np.percentile(row,50)}')
  print(f'75th %ile: {np.percentile(row,75)}')
  print(f'mean: {np.mean(row)}')
  print(f'median: {np.median(row)}')
  print(f'standard deviation: {np.std(row)}')

array with absolute values: [[1 2 3]
 [4 5 6]]
25th %ile for flattened array: -3.5
50th %ile for flattened array: -0.5
75th %ile for flattened array: 2.5
mean for flattened array: -0.5
median for flattened array: -0.5
standard deviation for flattened array: 3.8622100754188224
column 1
25th %ile: -2.75
50th %ile: -1.5
75th %ile: -0.25
mean: -1.5
median: -1.5
standard deviation: 2.5
column 2
25th %ile: -0.25
50th %ile: 1.5
75th %ile: 3.25
mean: 1.5
median: 1.5
standard deviation: 3.5
column 3
25th %ile: -3.75
50th %ile: -1.5
75th %ile: 0.75
mean: -1.5
median: -1.5
standard deviation: 4.5
row 1
25th %ile: -0.5
50th %ile: 1.0
75th %ile: 2.0
mean: 0.6666666666666666
median: 1.0
standard deviation: 2.0548046676563256
row 2
25th %ile: -5.0
50th %ile: -4.0
75th %ile: 0.5
mean: -1.6666666666666667
median: -4.0
standard deviation: 4.784233364802441


In [16]:
a = np.array([-1.8, -1.6, -0.5, 0.5,1.6, 1.8, 3.0])
floor_a=np.floor(a)
ceil_a=np.ceil(a)
trunc_a=np.trunc(a)
round_a=np.trunc(a)
print(f'floor: {floor_a}')
print(f'ceil: {ceil_a}')
print(f'truncate: {trunc_a}')
print(f'rounded: {round_a}')

floor: [-2. -2. -1.  0.  1.  1.  3.]
ceil: [-1. -1. -0.  1.  2.  2.  3.]
truncate: [-1. -1. -0.  0.  1.  1.  3.]
rounded: [-1. -1. -0.  0.  1.  1.  3.]


In [19]:
array = np.array([10, 52, 62, 16, 16, 54, 453])
sorted_array=np.sort(array)
sorted_indices=np.argsort(array)
smallest_4=sorted_array[:4]
largest_5=sorted_array[-5:]
print(f'sorted array: {sorted_array}')
print(f'sorted indices: {sorted_indices}')
print(f'4 smallest elements: {smallest_4}')
print(f'5 largest elements: {largest_5}')

sorted array: [ 10  16  16  52  54  62 453]
sorted indices: [0 3 4 1 5 2 6]
4 smallest elements: [10 16 16 52]
5 largest elements: [ 16  52  54  62 453]


In [21]:
array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])
int_elements=array[array==np.floor(array)]
float_elements=array[array!=np.floor(array)]
print(f'int elements: {int_elements}')
print(f'float elements: {float_elements}')

int elements: [1. 2. 3. 2.]
float elements: [1.2 2.2]


In [22]:
import cv2
import numpy as np
def img_to_array(path):
    img_gray = cv2.imread(path, cv2.IMREAD_GRAYSCALE)
    if img_gray is not None and len(img_gray.shape) == 2:
        np.savetxt("image_gray.txt", img_gray, fmt='%d')
        print("Grayscale image saved as 'image_gray.txt'")
        return
    img_color = cv2.imread(path, cv2.IMREAD_COLOR)
    if img_color is not None and len(img_color.shape) == 3:
        img_rgb = cv2.cvtColor(img_color, cv2.COLOR_BGR2RGB)
        np.savetxt("image_rgb.txt", img_rgb.reshape(-1, 3), fmt='%d')
        print("RGB image saved as 'image_rgb.txt'")
        return
    print("Failed to load image.")
